### ISSUE TITLE
Conflict with Hardcore Ender Expansion

### ISSUE THREAD

**Issue by sceaduwe** [Emasher/EmashersMods#108]
HEE is apperently detecting a recipe registration error. I tracked the source of the problem to this mod. Output is as follows.

"Hardcore Ender Expansion has found a defective recipe and cannot proceed! Another mod is likely registering a recipe BEFORE registering blocks and items, which is considered a serious error! Please, remove other mods until this message stops appearing to find which mod causes the issue, and then report it to that mod's author."

**Comment by Tomson124** [comment]
Conflict with HEE still exists in most recent version (1.2.0.2), too.

**Comment by Emasher** [comment]
Can you post the full crash report?

**Comment by Tomson124** [comment]
http://pastebin.com/2drprD8X
The first part of the log file is cut off otherwise I couldn't upload it to pastebin.

**Comment by Emasher** [comment]
I think I've found the issue, so I'll make sure it's fixed in 1.2.0.2.

**Comment by Emasher** [comment]
I've changed the order some recipes and items are registered in, and removed a few out-dated recipes. I think that should fix the problem in 1.2.0.3. Let me know either way.

**Comment by Tomson124** [comment]
Yeah works totaly fine now.
Thanks for the quick fix.
