### ISSUE TITLE
Crash when activating a Burner

### ISSUE THREAD

**Issue by Leadcraft** [Emasher/EmashersMods#111]
Using 1.2.0.1 BETA for 1.7.10.

This happens to me with 100% reliability:

1. Place an empty socket.
2. Add a Burner and a Button module.
3. Link up the two through either a channel or a latch.
4. Press button.
5. Receive crash: http://paste.ee/p/99cAt

After relogging, the modules on the socket are now invisible.

Using an external redstone signal through a Redstone Input module also crashes.

**Comment by Emasher** [comment]
I've fixed the crash. Unfortunately, burners are now expensive tick wise, so use with care.
