### ISSUE TITLE
Crash when placing down Modular Socket

### ISSUE THREAD

**Issue by Yanniclord** [Emasher/EmashersMods#112]
So i am playing on a private server with my friend, and as i tried to place down the Modular Socket, we got both disconnected from the server and everytime we wanted to rejoin we got kicked again, so i had to remove the mod, unfortunatly there is no crashlog as the server doesnt crash, only client gets kicked instead. Way to reproduce: 

1: Place Modular Socket
2: Get kicked.

**Comment by nickdellhall** [comment]
Any update on this? I have the same problem using ET 1.2.0.1 in the DW1.7(1.0.3) pack.

Placed down modular socket, gets kicked. Any time I tried to login the server results in a kick. Solution was to TP myself in console while logging in, but approaching / loading the chunk w/ the modular socket results in a kick again.

Currently, trying to remove the block w/ MCedit. Will report back if that doesn't work.

**Comment by Kenshij** [comment]
Same here EngineersToolbox-1.2.0.1-BETA.jar
There is an issue with the sending from messages bitween server/client

an other had forgotten init() the message system ->
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/modification-development/2125679-solved-1-7-2-simpleimpl-message-sending-system

an other have sendet messages to client/server parallel but you can only send it to one side ->
http://www.minecraftforge.net/forum/index.php?topic=24197.0

PLEASE FIX i need the modpack to automate my factory ^___^

**Comment by nickdellhall** [comment]
Just to report back, the corrupted modular socket can be removed by MCedit and things will resume ok. I'm not keeping my hope up for a patch anytime soon, seems like development has come to a stall.

**Comment by Kenshij** [comment]
Have disabled the mod, so all blocks are removed ;) 
Thas bad to hear, ist a great mod.

**Comment by Emasher** [comment]
As I've stated on Twitter, I don't have time to work on the mod for another couple months at the earliest, but I do still view all of these bug reports. If someone else wants to fix the issue before then, and submits a pull request, I'll probably be able to find time to do a build and make an official release of it.

**Comment by Brycey92** [comment]
Thanks for the status update, Emasher!

**Comment by jacfalcon0** [comment]
I also am suffering from this issue :(

**Comment by Emasher** [comment]
Managed to fix this.
