### ISSUE TITLE
Infinite energy through MFR Rednet Energy Cables

### ISSUE THREAD

**Issue by Taschenmogul** [Emasher/EmashersMods#116]
As the title says I was (easily) able to get infinite energy by using MinefactoryReloaded's "Rednet Energy Cable"s for connecting my sockets.
Here's the details:

Put down a Modular Socket with an energy output cover, then connect a rednet energy cable to it (or several), then attach that to some energy consumer that works with those cables (modular sockets, TE energy cells, IC2 machines, etc.).
The result is the modular socket producing energy out of nowhere and feeding it to the consumer.

It is important not to place the modular socket after you placed the cable or the bug won't show.
This only seems to work with those MFR cables and only together with modular sockets; using other cables has not produced that effect for me, using MFR cables with other blocks than the modular sockets does also not produce the issue for me, so this might be a bug on MFR's site or yours or both, I don't know.

**(mod) versions:**
- Minecraft 1.7.10
- Forge .1232
- Recent Java 7
- EngineersToolbox-1.2.0.0-BETA
- MineFactoryReloaded-[1.7.10]2.8.0RC4-676
- CoFHCore-[1.7.10]3.0.0B8-36
- CoFHLib-[1.7.10]1.0.0B7-29

**Comment by Emasher** [comment]
Is this still an issue in 1.2.0.2 and more recent versions of the conflicting mods?

**Comment by Emasher** [comment]
Fixed.
