### ISSUE TITLE
Modules disappear on reload

### ISSUE THREAD

**Issue by CommodoreAlpha** [Emasher/EmashersMods#117]
I tested this in singleplayer with version 1.2.0.1 of Engineer's Toolbox. When I place an empty socket and put a module on it, exit the game, then reload the world, the socket appears to be entirely empty. Curiously enough, though, when I break the empty socket, all the modules I had placed on it beforehand dropped. Whether this is purely a visual bug or not is unknown to me.

EDIT: I can now confirm it's a visual bug; when any of the modules undergo any sort of graphic change, they reappear.

**Comment by Emasher** [comment]
I can't reproduce this with the latest code.
