### ISSUE TITLE
Client Disconnects from Server

### ISSUE THREAD

**Issue by CommodoreAlpha** [Emasher/EmashersMods#119]
When I placed a "Flux Pipe" from Engineer's Toolbox, my client instantly disconnected from my server. When I tried relogging, loading the chunk with that block inside of it disconnects my client. Clientside, I don't receive any errors, but serverside, I receive this error: http://pastebin.com/a8riCyyf

In singleplayer with the same mods installed, I do not run into any such problems.

**Comment by Kenshij** [comment]
Same here EngineersToolbox-1.2.0.1-BETA.jar
There is an issue with the sending from messages bitween server/client

an other had forgotten init() the message system ->
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/modification-development/2125679-solved-1-7-2-simpleimpl-message-sending-system

an other have sendet messages to client/server parallel but you can only send it to one side ->
http://www.minecraftforge.net/forum/index.php?topic=24197.0

PLEASE FIX i need the modpack to automate my factory ^___^

**Comment by Emasher** [comment]
Managed to fix this.
