### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MrBretze** [Emasher/EmashersMods#121]
EmashersMods project is abandon ?

**Comment by crunkazcanbe** [comment]
I hope not . I love this mod . Wish someone would update it to remove MJ support and fix all the bugs .

**Comment by jacfalcon0** [comment]
Such a good mod. Really hope to see it updated and bugs squashed. So sad to not see it in some of the newer modpacks.

**Comment by MonzterAssassin** [comment]
Might wanna go ask HardWire about that. He's on the forums and apparently he is doing just that :)

**Comment by MonzterAssassin** [comment]
You can find him in the last 2 pages of EMasher's latest 1.7.10 forum post for the mod.

**Comment by Emasher** [comment]
The project is not abandoned. I have begun work on it again.

The source code is not licensed in such a way that it permits updating the mod and releasing it publicly independently. The portions of the code that I have written are still under copyright regardless of the fact that the source code is available. If someone wishes to contribute to the project, they should do it through this repository.

**Comment by MrBretze** [comment]
Good news :)
