### ISSUE TITLE
Client disconnecting from server when certain liquids are in a tank.

### ISSUE THREAD

**Issue by Derpford** [Emasher/EmashersMods#124]
I placed down a Socket in a singleplayer creative-mode world. After placing a Tank Interface module on one side, I right-clicked on it with a Socket Remote set to configure tanks. I immediately received an error stating that I had been disconnected from the server, along with a button to send me back to the main menu.
I've put the relevant chunk of the log in a pastebin here: http://pastebin.com/kyQnn5wH
I've had this error with both 1.2.0.0 and 1.2.0.1.

**Comment by Emasher** [comment]
I can't reproduce this. What fluid was in the tank?

**Comment by Emasher** [comment]
Also, I changed the issue name to be more accurate.

**Comment by Emasher** [comment]
I think I know what caused this and may have fixed it in 1.2.0.2.

**Comment by Derpford** [comment]
The tank was empty. I just downloaded 12.0.0.2, however, and the issue
appears to be resolved.
