### ISSUE TITLE
[Suggestion] better internal inventory management for the furnance

### ISSUE THREAD

**Issue by Frontrider** [Emasher/EmashersMods#134]
I wanted to set up the socket in a way, that the installed furnance would output into an installed stirling generator (basicly, the classic generator+furnance combo for a self sustaining treefarm). When I set the machine output to inventory 2, I get the output.Altough it never shows up in inventory 2. Could the furnace output into a selected internal inventory?

For now, i'll go around with pipe.

**Comment by Emasher** [comment]
It's already possible to do this. Set the furnace to one inventory, and put the wood (I assume) in that inventory. Set the machine output to a second inventory and set the stirling generator to the same inventory. Make sure there isn't some sort of inventory block adjacent to the side with the machine output installed on it or the items will be output into that.
