### ISSUE TITLE
[Crash] rendering rf tools charged porter withing the socket

### ISSUE THREAD

**Issue by Frontrider** [Emasher/EmashersMods#135]
http://pastebin.com/uDnrPEhB

I tried to charge the thing with the engineer's toolbox charging module.(at the time it was easier than making an energetic infuser).

Not sure, whitch side is the source.
https://github.com/McJty/RFTools/issues/220

**Comment by Emasher** [comment]
Definitely a problem on my side. Can you update to ET 1.2.0.6 and post a new crash report from that?

Also, which tool were you using specifically?

**Comment by Frontrider** [comment]
Updated the mod.
The Portable teleporter thingy (can't recall the exact name), I will remove the socket from the game, since it prevents me from loading up the map.

**Comment by Emasher** [comment]
Could you post the 1.2.0.6 crash report?

**Comment by Frontrider** [comment]
its the same.

**Comment by Emasher** [comment]
Fixed in the code.
