### ISSUE TITLE
[bug] Sockets tend to disconnect from pipes (thermal dynamics tested)

### ISSUE THREAD

**Issue by Frontrider** [Emasher/EmashersMods#136]
http://imgur.com/OW0pIGc
http://imgur.com/OMcslVJ

Probably related to loading up the world/chunk. The ducts were connected before. 

Probably theres something fishy in the way how the blocks handle this sort of "dynamic Isidedness". If thats the chase, could ask KingLemming on how they solved in, within the thermal expansion machines.

**Comment by Emasher** [comment]
Those links are broken, but I know what you're talking about. I'd suggest reporting the issue to the Thermal Expansion developers for now.
