### ISSUE TITLE
Wool usage lookup crash with NEI

### ISSUE THREAD

**Issue by mathiasDJ** [Emasher/EmashersMods#139]
When I look up the usages of wool with NEI my client crashes when I switch to the Spinning Wheel recipes page. (I assume it's that page from reading the crash-report).

Crash-report: http://pastebin.com/gZ8SS6My
Using this pack: http://minecraft.curseforge.com/modpacks/232056-the-ryrypatpatpackpack
Engineer's Toolbox version: 1.2.2.0-BETA

**Comment by zwya** [comment]
I also get the same crash when I try looking up the recipe for string or usage of wool using NEI (Version 1.2.2.0-BETA).

**Comment by shadoxxhd** [comment]
same for me.

**Comment by Emasher** [comment]
Just a minor issue converting between Scala and Java lists.
