### ISSUE TITLE
[1.10.2] onCrafted() NullPointerException Server Console Spam

### ISSUE THREAD

**Issue by PotatoSauceVFX** [Emasher/EmashersMods#158]
A little while ago I started getting a bunch of cached exceptions in console and it made the console not usable. Turns out a player started using the Workshop tables and sure enough when he turned them off using red stone the errors stopped. Here's the snippet from the fml logs: http://pastebin.com/n6TPSjTc

**Comment by YuRaNnNzZZ** [comment]
https://github.com/EngineersMods/EngineersWorkshop/issues

**Comment by PotatoSauceVFX** [comment]
The Curse link for the mod needs to be updated then.
