### ISSUE TITLE
Latch toggle module for non-empty socket inventory/tank

### ISSUE THREAD

**Issue by Zymbal** [Emasher/EmashersMods#75]
While working on some automation with the fracker and the kiln, I was thinking it would be nice if there was a latch toggle module (or even appropriate purple latch settings on the inventory and tank modules) that could toggle one or more latches on if anything was in the inventory/tank and off if empty.

**Comment by Emasher** [comment]
I've removed the item and fluid detectors at this point. There is a planned feature that will likely allow for this functionality, but in a different way.
