### ISSUE TITLE
Gas multiplication

### ISSUE THREAD

**Issue by LemADEC** [Emasher/EmashersMods#98]
When collecting gas with fan, you get more than what you spent.
Setup:
- Make a 3x3 x4 high room
- In center top, place a Modular socket with 4 fans (horizontal), fluid output (down) and redstone (top with redstone block above)
- Below, use a Thermal Expansion fluid duct then a Reinforced portable tank
- Throw a vial (Toxic & Propene for example) in the room
- Wait for fans to fill the tank => 32+ buckets are collected, only 4 where in the vials

EngineersToolbox-1.1.8.4
GasCraft-2.0.4.4
CoFHCore-2.0.0.5
ThermalExpansion-3.0.0.7

**Comment by Emasher** [comment]
This isn't reproducible in the 1.7 versions. The result of the experiment was 3871 mB of gas ending up in the tank.
